stages:
  reproduce_table_task_1_cbow:
    cmd: cd external/table_repo && docker-compose up --build task_1_cbow
    deps:
    - external/table_repo/src
    - external/table_repo/Dockerfile
    - external/table_repo/docker-compose.yml
    - external/table_repo/data
    - external/table_repo/configurations
    outs:
    - external/table_repo/exp1/cbow_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp1/cbow_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp1/cbow_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp1/cbow_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1
    - external/table_repo/exp1/cbow_finetune_1_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp1/cbow_finetune_1_lr_0.001_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp1/cbow_finetune_1_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp1/cbow_finetune_1_lr_0.001_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1

  reproduce_table_task_1_bert:
    cmd: cd external/table_repo && docker-compose up --build task_1_bert
    deps:
    - external/table_repo/src
    - external/table_repo/Dockerfile
    - external/table_repo/docker-compose.yml
    - external/table_repo/data
    - external/table_repo/configurations
    outs:
    - external/table_repo/exp1/bert-base-uncased_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp1/bert-base-uncased_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp1/bert-base-uncased_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp1/bert-base-uncased_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1
    - external/table_repo/exp1/bert-base-uncased_finetune_1_lr_5e-05_schedule_linear_schedule_with_warmup_epoch_3_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp1/bert-base-uncased_finetune_1_lr_2e-05_schedule_linear_schedule_with_warmup_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp1/bert-base-uncased_finetune_1_lr_2e-05_schedule_linear_schedule_with_warmup_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp1/bert-base-uncased_finetune_1_lr_5e-05_schedule_linear_schedule_with_warmup_epoch_3_feature_edit-original_extra_1_seed_1

  reproduce_table_task_1_roberta:
    cmd: cd external/table_repo && docker-compose up --build task_1_roberta
    deps:
    - external/table_repo/src
    - external/table_repo/Dockerfile
    - external/table_repo/docker-compose.yml
    - external/table_repo/data
    - external/table_repo/configurations
    outs:
    - external/table_repo/exp1/roberta-base_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp1/roberta-base_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp1/roberta-base_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp1/roberta-base_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1
    - external/table_repo/exp1/roberta-base_finetune_1_lr_2e-05_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp1/roberta-base_finetune_1_lr_2e-05_schedule_linear_schedule_with_warmup_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp1/roberta-base_finetune_1_lr_2e-05_schedule_linear_schedule_with_warmup_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp1/roberta-base_finetune_1_lr_2e-05_schedule_linear_schedule_with_warmup_epoch_3_feature_edit-original_extra_1_seed_1

  reproduce_table_task_2_cbow:
    cmd: cd external/table_repo && docker-compose up --build task_2_cbow
    deps:
    - external/table_repo/src
    - external/table_repo/Dockerfile
    - external/table_repo/docker-compose.yml
    - external/table_repo/data
    - external/table_repo/configurations
    outs:
    - external/table_repo/exp2/cbow_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp2/cbow_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp2/cbow_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp2/cbow_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1
    - external/table_repo/exp2/cbow_finetune_1_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp2/cbow_finetune_1_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp2/cbow_finetune_1_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp2/cbow_finetune_1_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1

  reproduce_table_task_2_bert:
    cmd: cd external/table_repo && docker-compose up --build task_2_bert
    deps:
    - external/table_repo/src
    - external/table_repo/Dockerfile
    - external/table_repo/docker-compose.yml
    - external/table_repo/data
    - external/table_repo/configurations
    outs:
    - external/table_repo/exp2/bert-base-uncased_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp2/bert-base-uncased_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp2/bert-base-uncased_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp2/bert-base-uncased_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1
    - external/table_repo/exp2/bert-base-uncased_finetune_1_lr_5e-05_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp2/bert-base-uncased_finetune_1_lr_5e-05_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp2/bert-base-uncased_finetune_1_lr_2e-05_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp2/bert-base-uncased_finetune_1_lr_2e-05_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1

  reproduce_table_task_2_roberta:
    cmd: cd external/table_repo && docker-compose up --build task_2_roberta
    deps:
    - external/table_repo/src
    - external/table_repo/Dockerfile
    - external/table_repo/docker-compose.yml
    - external/table_repo/data
    - external/table_repo/configurations
    outs:
    - external/table_repo/exp2/roberta-base_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp2/roberta-base_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp2/roberta-base_finetune_0_lr_0.001_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp2/roberta-base_finetune_0_lr_0.0003_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1
    - external/table_repo/exp2/roberta-base_finetune_1_lr_2e-05_schedule_linear_schedule_with_warmup_epoch_3_feature_edit-context_extra_0_seed_1
    - external/table_repo/exp2/roberta-base_finetune_1_lr_2e-05_schedule_linear_schedule_with_warmup_epoch_3_feature_edit-original_extra_0_seed_1
    - external/table_repo/exp2/roberta-base_finetune_1_lr_2e-05_schedule_none_epoch_10_feature_edit-context_extra_1_seed_1
    - external/table_repo/exp2/roberta-base_finetune_1_lr_5e-05_schedule_none_epoch_10_feature_edit-original_extra_1_seed_1
  download_data:
    cmd: python3 laughing_net/data/download.py
    deps:
    - laughing_net/data/download.py
    params:
    - data.url
    - data.zip_file
    outs:
    - data/raw/semeval-2020-task-7-dataset
    - data/raw/semeval-2020-task-7-dataset.zip
  substitute_replacements_task_1_train:
    cmd: python3 laughing_net/features/substitute_replacements.py --input data/raw/semeval-2020-task-7-dataset/subtask-1/train.csv
      --output data/interim/task-1/train_sub.csv
    deps:
    - data/raw/semeval-2020-task-7-dataset/subtask-1/train.csv
    - laughing_net/features/substitute_replacements.py
    outs:
    - data/interim/task-1/train_sub.csv
  substitute_replacements_task_1_dev:
    cmd: python3 laughing_net/features/substitute_replacements.py --input data/raw/semeval-2020-task-7-dataset/subtask-1/dev.csv
      --output data/interim/task-1/dev_sub.csv
    deps:
    - data/raw/semeval-2020-task-7-dataset/subtask-1/dev.csv
    - laughing_net/features/substitute_replacements.py
    outs:
    - data/interim/task-1/dev_sub.csv
  substitute_replacements_task_1_test:
    cmd: python3 laughing_net/features/substitute_replacements.py --input data/raw/semeval-2020-task-7-dataset/subtask-1/test.csv
      --output data/interim/task-1/test_sub.csv
    deps:
    - data/raw/semeval-2020-task-7-dataset/subtask-1/test.csv
    - laughing_net/features/substitute_replacements.py
    outs:
    - data/interim/task-1/test_sub.csv
  tfidf_task_1_train:
    cmd: python3 laughing_net/features/tfidf.py --input data/interim/task-1/train_sub.csv
      --output data/interim/task-1/train_tfidf.npz --encoder artifacts/tfidf_encoder.pkl
      --fit
    deps:
    - data/interim/task-1/train_sub.csv
    - laughing_net/features/tfidf.py
    outs:
    - artifacts/tfidf_encoder.pkl
    - data/interim/task-1/train_tfidf.npz
  tfidf_task_1_dev:
    cmd: python3 laughing_net/features/tfidf.py --input data/interim/task-1/dev_sub.csv
      --output data/interim/task-1/dev_tfidf.npz --encoder artifacts/tfidf_encoder.pkl
    deps:
    - data/interim/task-1/dev_sub.csv
    - laughing_net/features/tfidf.py
    - artifacts/tfidf_encoder.pkl
    outs:
    - data/interim/task-1/dev_tfidf.npz
  tfidf_task_1_test:
    cmd: python3 laughing_net/features/tfidf.py --input data/interim/task-1/test_sub.csv
      --output data/interim/task-1/test_tfidf.npz --encoder artifacts/tfidf_encoder.pkl
    deps:
    - data/interim/task-1/test_sub.csv
    - laughing_net/features/tfidf.py
    - artifacts/tfidf_encoder.pkl
    outs:
    - data/interim/task-1/test_tfidf.npz
