data:
  anek:
    split:
      test_size: 0.1
      random_state: 42

models:
  rugpt:
    name: "sberbank-ai/rugpt3small_based_on_gpt2"
    checkpoint_name: "rugpt_ckpt"
    output_name: "rugpt_ckpt"
    stages:
      train:
        num_train_epochs: 20
        per_device_train_batch_size: 8
        per_device_eval_batch_size: 16
        eval_steps: 500
        evaluation_strategy: "steps"
        save_total_limit: 3
        warmup_steps: 500
        load_best_model_at_end: true
        overwrite_output_dir: true

      generation:
        min_length: 50
        max_length: 500
        temperature: 0.3
        top_k: 60
        top_p: 0.8
        repetition_penalty: 1.2
        num_return_sequences: 3
        do_sample: true
